### ISSUE TITLE
Getting a "no editor command" error when opening a markdown file in neovim

### ISSUE THREAD

**Issue by bitboxer** [danielbmarques/vim-ditto#1]
I am using NeoVim and when opening a markdown file I get this error:

```
Fehler beim Ausführen von "function <SNR>125_getGoodWords":
Zeile    4:
E492: Kein Editorbefehl:         writefile([], g:dittofile)
```

Can you help me debug this? Thanks!

**Comment by dbmrq** [comment]
Uhm, that's odd. What `writefile([], g:dittofile)` does is just to write an empty file at the `g:dittofile` path. It seems like NeoVim's `writefile()` works a little differently, though: https://github.com/neovim/neovim/issues/4889

I'll look into it as soon as I can, but I never used NeoVim and I'll have to configure it and all, so it might take a while. If you want to get started, first I'd check for special characters in the path, like mentioned in that NeoVim bug. If there's nothing wrong there, I'd try adding an empty string to the array that's written to the file: `writefile([""], g:dittofile)`. If that still doesn't work, that whole command could be replaced for a simple `touch`, I guess. That might actually be better anyway.

So, well, you can try all that, and let me know if it gets you anywhere. As soon as I have the time I'll install NeoVim and take a look myself.

**Comment by bitboxer** [comment]
Changing it to `writefile([""], g:dittofile)` did not help, but changing it to `call system('touch ' . g:dittofile)` worked and the error is gone. But I don't know if this is the best practice to touch a file though :wink: .

Sorry for the NeoVim troubles.

**Comment by dbmrq** [comment]
Did you try adding any good and/or bad words with `<Plug>DittoGood` and `<Plug>DittoBad`? That also uses `writefile()`, so maybe it won't work either. I don't know what could be happening there except maybe that encoding issue with NeoVim.

**Comment by bitboxer** [comment]
That works. `DittoGood` successfully adds the word to the file.

**Comment by dbmrq** [comment]
Uhm, alright, NeoVim's `writefile()` just doesn't _create_ the file then. I'll add a check and use `touch` if the user has NeoVim. Thanks. :)

**Comment by dbmrq** [comment]
Ok, that's embarrassing: now I managed to look into it and it actually has nothing to do with NeoVim. I just forgot to use `call` before `writefile()` 😳. So now it should work properly and it's not necessary to call `touch`.

**Comment by bitboxer** [comment]
Just tested and it works perfectly. Thanks for this plugin and your quick help!
