### ISSUE TITLE
Should default to a sensible highlight group.

### ISSUE THREAD

**Issue by tstelzer** [danielbmarques/vim-ditto#4]
_First of all, thanks for your plugin, works particularly well with wordy!_

The plugin defaults to the `Error` highlight group. I guess that *will* catch your attention, but I would prefer one that makes more semantic sense. `SpellRare` comes to mind.

I realize there is an option to change it, but sensible defaults are desirable!

**Comment by dbmrq** [comment]
Makes sense, I'll change it as soon as I have the time. Or you can make a PR if you're up for it, in which case remember to change the readme and docs. :)
