### ISSUE TITLE
Something wrong with non-ASCII characters

### ISSUE THREAD

**Issue by mcepl** [danielbmarques/vim-ditto#7]
![screenshot](https://user-images.githubusercontent.com/198999/28250426-443b4fde-6a68-11e7-94b1-1fc562121ec0.png)

Not sure what's the problem, but it seems that vim-ditto cannot distinguish between a part of the word “některé”  (“some” in Czech) and “které” (“which” in Czech). Both ``encoding`` and ``fileencoding`` are ``utf-8``.

**Comment by dbmrq** [comment]
This should be fixed with the latest commit. Thanks. :)

**Comment by mcepl** [comment]
Yes, works. Perfect! Thank you.
