### ISSUE TITLE
Helptags broken

### ISSUE THREAD

**Issue by PetraOleum** [danielbmarques/vim-ditto#9]
https://github.com/dbmrq/vim-ditto/blob/22ac9a91dc62827a37bda2f15f1558eb1ecb30dc/doc/ditto.txt#L139

Seems to be a duplicate tag with this line? Needs to just be "<Plug>Ditto" and not "<Plug>DittoNext".

**Comment by dbmrq** [comment]
Fixed it, thanks for letting me know. :)
